# Balanced configuration - good accuracy with reasonable performance
# Target: 60fps with ~100 bodies, suitable for most use cases

[physics]
gravitational_constant = 10.0
body_count = 100
octree_theta = 0.5                    # Standard Barnes-Hut parameter
octree_leaf_threshold = 10            # Balanced node distribution
body_distribution_sphere_radius_multiplier = 3.0
body_distribution_min_distance = 20.0
min_body_radius = 1.0
max_body_radius = 5.0
force_calculation_min_distance = 10.0
force_calculation_max_force = 10000.0

[physics.initial_velocity]
enabled = true
min_speed = 5.0
max_speed = 20.0
velocity_mode = "Random"
tangential_bias = 0.7

[rendering]
min_temperature = 3000.0
max_temperature = 15000.0
bloom_intensity = 100.0             # Standard bloom
saturation_intensity = 3.0          # Standard saturation
camera_radius_multiplier = 4.0      # Default viewing distance