# High accuracy configuration for scientific/precise simulations
# Target: Maximum accuracy, performance secondary

version = 5

[physics]
gravitational_constant = 10.0
body_count = 100
octree_theta = 0.1                    # Very low theta = high accuracy
octree_leaf_threshold = 4             # Small leaves = precise calculations
body_distribution_sphere_radius_multiplier = 3.0
body_distribution_min_distance = 20.0
min_body_radius = 1.0
max_body_radius = 5.0
force_calculation_min_distance = 10.0
force_calculation_max_force = 10000.0
collision_restitution = 0.8
collision_friction = 0.1

[physics.initial_velocity]
type = "OrbitWithPerturbation"
scale = 1.0
perturbation = 0.1

[rendering]
camera_distance_multiplier = 3.0
camera_look_at_barycenter = true
touch_controls_enabled = true
touch_sensitivity = 1.0
star_point_size_multiplier = 1.5