# High accuracy configuration for scientific/precise simulations
# Target: Maximum accuracy, performance secondary

version = 6

[physics]
gravitational_constant = 10.0
body_count = 100
octree_theta = 0.1                    # Very low theta = high accuracy
octree_leaf_threshold = 4             # Small leaves = precise calculations
body_distribution_sphere_radius_multiplier = 3.0
body_distribution_min_distance = 20.0
min_body_radius = 1.0
max_body_radius = 5.0
force_calculation_min_distance = 10.0
force_calculation_max_force = 10000.0

[physics.initial_velocity]
enabled = true
min_speed = 2.0                     # Lower speeds for stability
max_speed = 10.0
velocity_mode = "Orbital"           # More predictable motion
tangential_bias = 0.9               # Strong orbital tendency

[rendering]
min_temperature = 3000.0
max_temperature = 15000.0
bloom_intensity = 150.0             # Higher quality visuals
saturation_intensity = 4.0          # Enhanced color depth
camera_radius_multiplier = 4.0