# Stress test configuration for extreme scenarios
# Target: Test limits with many bodies

version = 6

[physics]
gravitational_constant = 10.0
body_count = 10000                    # High body count for stress testing
octree_theta = 0.8                    # Slightly relaxed for performance
octree_leaf_threshold = 20            # Moderate leaf size
body_distribution_sphere_radius_multiplier = 5.0  # Larger distribution
body_distribution_min_distance = 15.0
min_body_radius = 0.5
max_body_radius = 3.0
force_calculation_min_distance = 5.0
force_calculation_max_force = 50000.0

[physics.initial_velocity]
enabled = true
min_speed = 10.0
max_speed = 30.0
velocity_mode = "Random"
tangential_bias = 0.5               # More chaotic for stress testing

[rendering]
min_temperature = 3000.0
max_temperature = 15000.0
bloom_intensity = 50.0              # Less bloom effect
saturation_intensity = 2.0          # Less color saturation
camera_radius_multiplier = 6.0      # Zoom out more for many bodies