name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type to release'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - rc
          - beta
          - alpha
      dry_run:
        description: 'Perform a dry run (no actual release)'
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  release:
    name: Create release with cargo-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-release
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-release

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run cargo-release (dry run)
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "Running in dry-run mode..."
          cargo release ${{ github.event.inputs.version }} --verbose

      - name: Run cargo-release
        if: github.event.inputs.dry_run == 'false'
        run: |
          echo "Creating release..."
          cargo release ${{ github.event.inputs.version }} --execute --no-confirm
          
          # Push the commits and tags
          git push origin main --follow-tags
