name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      issues: write
      checks: write

  build:
    needs: ci
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      id-token: write
      attestations: write

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List artifacts
        run: ls -la artifacts/

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
          draft: false
          prerelease: false
          name: Stardrift v${{ steps.version.outputs.version }}
          body: |
            ## Downloads
            
            ### Desktop Installers
            - **Linux** (Debian/Ubuntu)
              - x86_64: `stardrift-${{ steps.version.outputs.version }}-x86_64-unknown-linux-gnu.deb`
              - ARM64: `stardrift-${{ steps.version.outputs.version }}-aarch64-unknown-linux-gnu.deb`
            - **Windows** (**currently not working!**)
              - x86_64: `stardrift-${{ steps.version.outputs.version }}-x86_64-pc-windows-msvc.msi`
              - ARM64: `stardrift-${{ steps.version.outputs.version }}-aarch64-pc-windows-msvc.msi`
            - **macOS**
              - Intel: `stardrift-${{ steps.version.outputs.version }}-x86_64-apple-darwin.dmg`
              - Apple Silicon: `stardrift-${{ steps.version.outputs.version }}-aarch64-apple-darwin.dmg`
            
            ### Portable Binaries
            - **Linux**
              - x86_64: `stardrift-${{ steps.version.outputs.version }}-x86_64-unknown-linux-gnu.tar.gz`
              - ARM64: `stardrift-${{ steps.version.outputs.version }}-aarch64-unknown-linux-gnu.tar.gz`
            - **Windows**
              - x86_64: `stardrift-${{ steps.version.outputs.version }}-x86_64-pc-windows-msvc.zip`
              - ARM64: `stardrift-${{ steps.version.outputs.version }}-aarch64-pc-windows-msvc.zip`
            - **macOS**
              - Intel: `stardrift-${{ steps.version.outputs.version }}-x86_64-apple-darwin.tar.gz`
              - Apple Silicon: `stardrift-${{ steps.version.outputs.version }}-aarch64-apple-darwin.tar.gz`
            
            ### WebAssembly
            - `stardrift-${{ steps.version.outputs.version }}-wasm.tar.gz` - Web build with trail rendering
            
            All downloads include SHA256 checksums for verification.
            
            ### Security Notices
            
            #### macOS
            The macOS binaries are ad-hoc signed but not notarized. When first running:
            1. **For .dmg files**: Right-click the DMG and select "Open" 
            2. **For command-line binaries**: Either right-click and select "Open" in Finder, or run:
               ```bash
               xattr -cr /path/to/stardrift
               ```
            
            #### Windows
            Windows SmartScreen may warn about the executable. To run:
            1. Click "More info" on the SmartScreen dialog
            2. Click "Run anyway"
            
            ## What's Changed
            
            See below for full changelog.