name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  # Run CI checks before building
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      issues: write
      checks: write

  # Use the reusable workflow for building
  build:
    needs: ci
    uses: ./.github/workflows/build-binaries.yml
    permissions:
      contents: read
      id-token: write
      attestations: write

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: List artifacts
        run: ls -la artifacts/

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
          generate_release_notes: true
          draft: false
          prerelease: false
          name: Stardrift v${{ steps.version.outputs.version }}
          body: |
            ## Downloads
            
            ### Desktop Installers
            - **Linux**: `.deb` packages for Debian/Ubuntu (x86_64, ARM64)
            - **Windows**: `.msi` installers (x86_64, ARM64)
            - **macOS**: `.dmg` disk images (Intel, Apple Silicon)
            
            ### Portable Binaries
            - **Linux**: `stardrift-x86_64-unknown-linux-gnu.tar.gz` (x86_64), `stardrift-aarch64-unknown-linux-gnu.tar.gz` (ARM64)
            - **Windows**: `stardrift-x86_64-pc-windows-msvc.zip` (x86_64), `stardrift-aarch64-pc-windows-msvc.zip` (ARM64)
            - **macOS**: `stardrift-x86_64-apple-darwin.tar.gz` (Intel), `stardrift-aarch64-apple-darwin.tar.gz` (Apple Silicon)
            
            ### WebAssembly
            - **WASM**: `stardrift-wasm.tar.gz` - Web build with trail rendering
            
            All downloads include SHA256 checksums for verification.
            
            ### Security Notices
            
            #### macOS
            The macOS binaries are ad-hoc signed but not notarized. When first running:
            1. **For .dmg files**: Right-click the DMG and select "Open" 
            2. **For command-line binaries**: Either right-click and select "Open" in Finder, or run:
               ```bash
               xattr -cr /path/to/stardrift
               ```
            
            #### Windows
            Windows SmartScreen may warn about the executable. To run:
            1. Click "More info" on the SmartScreen dialog
            2. Click "Run anyway"
            
            The binaries are signed with a self-signed certificate for basic integrity verification.
            
            ## What's Changed
            
            See below for full changelog.