name: Test Release Build

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Test specific platforms (leave empty to test all)'
        required: false
        default: ''
        type: string

permissions:
  contents: read

jobs:
  # Use the reusable workflow for test builds
  test-build:
    uses: ./.github/workflows/build-binaries.yml
    permissions:
      contents: read
      id-token: write
      attestations: write
    with:
      upload-artifacts: true
      artifact-prefix: 'test-build'
      retention-days: 1